package com.innowise.authservice.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * @ClassName Credential
 * @Description  Represents authentication credentials associated with a specific user.
 * @Author dshparko
 * @Date 07.10.2025 15:08
 * @Version 1.0
 */
@Entity
@Table(name = "credentials")
@Getter
@Setter
@NoArgsConstructor
public class Credential {
    /**
     * Primary key of the credential record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique email used for authentication.
     * Must be non-null and unique across all credentials.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Secure hash of the user's password.
     * Typically generated using SHA-256 or a stronger algorithm with salt.
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /**
     * Cryptographic salt used during password hashing.
     * Stored in Base64 format.
     */
    @Column(nullable = false)
    private String salt;

    /**
     * Associated user entity.
     * This is a mandatory one-to-one relationship.
     */
    @OneToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
}
