package com.innowise.authservice.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * @ClassName Role
 * @Description Represents a system-level role assigned to a user.
 * @Author dshparko
 * @Date 04.10.2025 19:14
 * @Version 1.0
 */
@Entity
@NoArgsConstructor
@Setter
@Getter
@Table(name = "roles")
public class Role {
    /**
     * Primary key of the role record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique name of the role (e.g., "ADMIN", "MODERATOR", "USER").
     * Used for access control and permission mapping.
     */
    @Column(name = "role_name", nullable = false, unique = true)
    private String name;
}
