package com.innowise.authservice.model.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

/**
 * @ClassName User
 * @Description Represents a system user within the authentication domain.
 * @Author dshparko
 * @Date 04.10.2025 18:38
 * @Version 1.0
 */
@Entity
@NoArgsConstructor
@Setter
@Getter
@Table(name = "users")
public class User {
    /**
     * Primary key of the user record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * One-to-one relationship with {@link Credential}.
     * Mapped by the {@code user} field in {@link Credential}.
     * Cascade type ALL ensures credentials are persisted/removed with the user.
     */
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
    private Credential credential;

    /**
     * Many-to-one relationship with {@link Role}.
     * Defines the user's access level and permissions.
     */
    @JoinColumn(name = "role_id", nullable = false)
    @ManyToOne
    private Role role;

    /**
     * Date when the user was created.
     * Automatically set before persistence.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDate createdAt;

    /**
     * Indicates whether the user is active.
     * Defaults to {@code true} on creation.
     */
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;

    /**
     * Initializes {@code createdAt} and {@code isActive} before persisting the entity.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDate.now();
        this.isActive = true;
    }
}
